version: '3.8'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./fakeanalyzer.sql:/docker-entrypoint-initdb.d/fakeanalyzer.sql

volumes:
  db_data: